sonar.projectKey=portfolio
sonar.projectName=portfolio
sonar.sources=apps,packages
sonar.exclusions=**/node_modules/**,**/.next/**,**/.svelte-kit/**,**/dist/**,**/build/**,**/static/**
sonar.host.url=http://localhost:9000
sonar.sourceEncoding=UTF-8
